services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - mynetwork

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - mynetwork
    ports:
      - "5432:5432"

  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ".:/app"
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=gsfdgsdfgdfsgdfsgsdf
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=root
      - DJANGO_SUPERUSER_EMAIL=root@root.com
      - DJANGO_SUPERUSER_PASSWORD=root
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:

