# Generated by Django 5.1.3 on 2024-11-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_role_order'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
