import type { Metadata } from "next";
import "./globals.css";
import "../app/(components)/NavBar/index.css"
import DashBoardWrapper from "./dashBoardWrapper";
import StoreProvider from "./StoreProvider"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
      <body>
        <DashBoardWrapper>{children}</DashBoardWrapper>
      </body>
      </StoreProvider>
    </html>
  );
}
