# Generated by Django 5.1.3 on 2024-11-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_rename_employee_task_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='employee',
            new_name='executor',
        ),
    ]
